[package]
name = "evaluator"
version = "0.2.3"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "6.1.0"
serde = "1.0.219"
sorted-vec = "0.8.6"
